#!/usr/bin/env bash
set -euo pipefail

web_root="/var/www/qmzg-training"
releases_dir="${web_root}/releases"
current_link="${web_root}/current"
nginx_target="/etc/nginx/conf.d/qmzg.conf"
state_dir="/var/lib/qmzg-saas-web"
state_file="${state_dir}/last-deploy.env"

log() {
    printf '%s\n' "$*"
}

require_root() {
    if [[ "${EUID}" -ne 0 ]]; then
        log "ERROR: run as root on the ECS"
        exit 2
    fi
}

validate_artifact() {
    local artifact="$1"
    [[ -f "${artifact}/index.html" ]] || {
        log "ERROR: index.html is missing from ${artifact}"
        exit 3
    }
    [[ -d "${artifact}/static" ]] || {
        log "ERROR: static/ is missing from ${artifact}"
        exit 3
    }
}

restore_previous() {
    local previous_release="$1"
    local config_backup="$2"

    if [[ -n "${config_backup}" && -f "${config_backup}" ]]; then
        install -o root -g root -m 0644 "${config_backup}" "${nginx_target}"
    fi

    if [[ -n "${previous_release}" && -d "${previous_release}" ]]; then
        ln -sfn "${previous_release}" "${current_link}.next"
        mv -Tf "${current_link}.next" "${current_link}"
    elif [[ -L "${current_link}" ]]; then
        unlink "${current_link}"
    fi

    nginx -t
    systemctl reload nginx
}

deploy() {
    local artifact="$1"
    local nginx_source="$2"
    local stamp release previous_release config_backup

    validate_artifact "${artifact}"
    [[ -f "${nginx_source}" ]] || {
        log "ERROR: Nginx source config is missing: ${nginx_source}"
        exit 3
    }

    stamp="$(date -u +%Y%m%dT%H%M%SZ)"
    release="${releases_dir}/${stamp}"
    previous_release=""
    config_backup=""

    install -d -o root -g nginx -m 0755 "${web_root}" "${releases_dir}" "${state_dir}"
    install -d -o root -g nginx -m 0755 "${release}"
    cp -a "${artifact}/." "${release}/"
    chown -R root:nginx "${release}"
    find "${release}" -type d -exec chmod 0755 {} +
    find "${release}" -type f -exec chmod 0644 {} +

    if [[ -L "${current_link}" ]]; then
        previous_release="$(readlink -f "${current_link}")"
    fi
    if [[ -f "${nginx_target}" ]]; then
        config_backup="${nginx_target}.backup-${stamp}"
        cp -a "${nginx_target}" "${config_backup}"
    fi

    install -o root -g root -m 0644 "${nginx_source}" "${nginx_target}"
    if ! nginx -t; then
        log "ERROR: nginx -t failed; restoring previous config"
        restore_previous "${previous_release}" "${config_backup}"
        exit 4
    fi

    ln -sfn "${release}" "${current_link}.next"
    mv -Tf "${current_link}.next" "${current_link}"
    systemctl reload nginx

    # systemctl reload returns after signalling the master; an old worker can
    # still serve one request while the new static server block is activating.
    local checks_ready="false"
    for _ in $(seq 1 20); do
        if curl -fsS --max-time 5 http://127.0.0.1/health >/dev/null && \
           curl -fsS --max-time 5 http://127.0.0.1/ | grep -Fq '擎梦智骨训练平台'; then
            checks_ready="true"
            break
        fi
        sleep 0.5
    done

    if [[ "${checks_ready}" != "true" ]]; then
        log "ERROR: post-deploy checks failed; rolling back"
        restore_previous "${previous_release}" "${config_backup}"
        exit 5
    fi

    {
        printf 'PREVIOUS_RELEASE=%q\n' "${previous_release}"
        printf 'CONFIG_BACKUP=%q\n' "${config_backup}"
        printf 'DEPLOYED_RELEASE=%q\n' "${release}"
    } >"${state_file}"
    chmod 0600 "${state_file}"

    log "DEPLOYED_RELEASE=${release}"
    log "PREVIOUS_RELEASE=${previous_release:-none}"
    log "CONFIG_BACKUP=${config_backup:-none}"
    log "HEALTH_CHECK=PASS"
    log "ROOT_CHECK=PASS"
}

rollback() {
    [[ -f "${state_file}" ]] || {
        log "ERROR: no rollback state found at ${state_file}"
        exit 6
    }

    # The state file is root-owned, mode 0600, and contains only shell-escaped
    # paths generated by this script.
    # shellcheck disable=SC1090
    source "${state_file}"
    restore_previous "${PREVIOUS_RELEASE:-}" "${CONFIG_BACKUP:-}"
    log "ROLLBACK=PASS"
}

require_root
case "${1:-}" in
    deploy)
        [[ "$#" -eq 3 ]] || {
            log "Usage: $0 deploy <dist-directory> <nginx-config>"
            exit 2
        }
        deploy "$2" "$3"
        ;;
    rollback)
        [[ "$#" -eq 1 ]] || {
            log "Usage: $0 rollback"
            exit 2
        }
        rollback
        ;;
    *)
        log "Usage: $0 {deploy <dist-directory> <nginx-config>|rollback}"
        exit 2
        ;;
esac
